### ISSUE TITLE
TOPIQ Test

### ISSUE THREAD

**Issue by lqz2** [chaofengc/IQA-PyTorch#231]
I retrained the TOPIQ model on the koniq10k dataset according to the settings in `train_TOPIQ_res50_koniq.yaml`. However, when I tested it using the command `python benchmark_results.py --metric_opt options/example_benchmark_metric_opts.yml -d koniq10k`, I encountered an error while loading the model weights. My `example_benchmark_metric_opts.yml` configuration is as follows:

```
custom_metric:
  metric_opts:
    type: CFANet
    pretrained: True
    pretrained_model_path: ./experiments/002_CFANet_Res50_koniq_archived_20241212_160337/models/net_best.pth
    crop_size: [384, 384]
    # [other possible options]
  metric_mode: NR
```
![image](https://github.com/user-attachments/assets/af573fe1-b5a1-4f1a-afb2-1cd8bf2526be)

Please advise on how to resolve this issue. Looking forward to your response.
